# Generated by Django 5.2.5 on 2025-12-10 06:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('weight_kg', models.FloatField()),
                ('height_cm', models.FloatField()),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('pattern_arc', models.IntegerField(default=0)),
                ('pattern_whorl', models.IntegerField(default=0)),
                ('pattern_loop', models.IntegerField(default=0)),
                ('risk_score', models.FloatField()),
                ('risk_level', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patient_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
