# Generated by Django 5.2.5 on 2025-12-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='donation_eligibility_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
