"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from corsheaders.defaults import default_headers
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = os.getenv("SECRET_KEY", "django-dev-key-replace-in-production")

DEBUG = os.getenv("DEBUG", "True") == "True"

# Parse ALLOWED_HOSTS from environment variable
allowed_hosts_env = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1")

# Handle wildcard '*' for allowing all hosts (use cautiously)
if allowed_hosts_env.strip() == "*":
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(",") if host.strip()]

# Always include Railway's internal domain if running on Railway
if os.getenv("RAILWAY_ENVIRONMENT"):
    railway_domain = os.getenv("RAILWAY_PUBLIC_DOMAIN")
    if railway_domain and railway_domain not in ALLOWED_HOSTS and "*" not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(railway_domain)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "api.apps.ApiConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Added for static files
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# CORS Configuration
# Parse explicit allowed origins from environment
CORS_ALLOWED_ORIGINS = [
    origin.strip() 
    for origin in os.getenv("CORS_ALLOWED_ORIGINS", "http://localhost:3000,http://localhost:8001").split(",")
    if origin.strip()
]

# Allow Vercel preview deployments using regex
# This matches URLs like: https://thesis-project-5tu3-*.vercel.app
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://thesis-project-5tu3.*\.vercel\.app$",  # Vercel preview deployments
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [*default_headers, "x-api-key"]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database - Using Supabase PostgreSQL
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url  # noqa: E402

# Default to SQLite for local testing, PostgreSQL for production
DATABASE_URL = os.getenv("DATABASE_URL", f"sqlite:///{BASE_DIR / 'db.sqlite3'}")

DATABASES = {"default": dj_database_url.parse(DATABASE_URL, conn_max_age=600)}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files (generated PDFs, QR codes, local records)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ==============================================================================
# SECURITY SETTINGS
# ==============================================================================

# HTTPS/SSL Settings (enabled in production only)
SECURE_SSL_REDIRECT = not DEBUG  # Force HTTPS in production
SESSION_COOKIE_SECURE = not DEBUG  # Only send session cookie over HTTPS
CSRF_COOKIE_SECURE = not DEBUG  # Only send CSRF cookie over HTTPS
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")  # For reverse proxy

# CSRF Trusted Origins
# Parse from environment variable
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("CSRF_TRUSTED_ORIGINS", "http://localhost:3000").split(",")
    if origin.strip()
]

# Add Vercel preview domain pattern if specified
# For Vercel previews, you can set: VERCEL_PREVIEW_PATTERN=https://*.vercel.app
vercel_preview_pattern = os.getenv("VERCEL_PREVIEW_PATTERN")
if vercel_preview_pattern:
    # Note: Django doesn't support wildcards in CSRF_TRUSTED_ORIGINS
    # You'll need to add each preview URL manually or disable CSRF for API endpoints
    pass

# HTTP Strict Transport Security (HSTS)
# Tells browsers to only use HTTPS for this domain
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Security Headers
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME-sniffing
SECURE_BROWSER_XSS_FILTER = True  # Enable XSS filter
X_FRAME_OPTIONS = "DENY"  # Prevent clickjacking

# Content Security Policy (CSP)
# Prevents XSS attacks by controlling where resources can be loaded from
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'")  # unsafe-inline needed for some libraries
CSP_IMG_SRC = ("'self'", "data:", "https:")
CSP_FONT_SRC = ("'self'", "https:")
CSP_CONNECT_SRC = ("'self'",)
CSP_FRAME_ANCESTORS = ("'none'",)

# Session Security
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = "Lax"  # CSRF protection
SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_SAVE_EVERY_REQUEST = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# CSRF Security
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_USE_SESSIONS = False
CSRF_COOKIE_AGE = 31449600  # 1 year

# Password Security
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",  # Most secure
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
]

# Logging Configuration
# Build handlers dict based on DEBUG mode
_log_handlers = {
    "console": {
        "level": "DEBUG" if DEBUG else "INFO",
        "class": "logging.StreamHandler",
        "formatter": "verbose",
    },
}

# Only add file handler in DEBUG mode (when logs directory exists)
if DEBUG:
    _log_handlers["file"] = {
        "level": "ERROR",
        "class": "logging.FileHandler",
        "filename": BASE_DIR / "logs" / "errors.log",
        "formatter": "verbose",
    }

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": _log_handlers,
    "root": {
        "handlers": ["console"],
        "level": "DEBUG" if DEBUG else "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.security": {
            # Only use file handler in DEBUG mode
            "handlers": ["console", "file"] if DEBUG else ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "api": {
            # Only use file handler in DEBUG mode
            "handlers": ["console", "file"] if DEBUG else ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
    },
}

# ==============================================================================
# PERFORMANCE SETTINGS
# ==============================================================================

# Database Connection Pooling
DATABASES["default"]["CONN_MAX_AGE"] = 600

# Only add PostgreSQL-specific options if using PostgreSQL
if "postgresql" in DATABASE_URL or "postgres" in DATABASE_URL:
    DATABASES["default"]["OPTIONS"] = {
        "connect_timeout": 10,
    }

# Cache (for future use with Redis)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
        "TIMEOUT": 300,
        "OPTIONS": {"MAX_ENTRIES": 1000},
    }
}

# ==============================================================================
# API SPECIFIC SETTINGS
# ==============================================================================

# Rate Limiting (requests per minute)
RATE_LIMIT_ENABLED = os.getenv("RATE_LIMIT_ENABLED", "True") == "True"
RATE_LIMIT_DEFAULT = int(os.getenv("RATE_LIMIT_DEFAULT", "60"))
RATE_LIMIT_ANALYZE = int(os.getenv("RATE_LIMIT_ANALYZE", "20"))
RATE_LIMIT_UPLOAD = int(os.getenv("RATE_LIMIT_UPLOAD", "100"))

# File Upload Limits
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB max request size
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB max file size

# Timeout Settings
REQUEST_TIMEOUT = int(os.getenv("REQUEST_TIMEOUT", "30"))

# ==============================================================================
# SECURITY HEADERS (Production)
# ==============================================================================

if not DEBUG:
    # HTTPS/SSL Settings
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Security Headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = "DENY"
    
    # Referrer Policy
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# ==============================================================================
# DEVELOPMENT OVERRIDES
# ==============================================================================

if DEBUG:
    # Disable some security features in development for easier testing
    CORS_ALLOW_ALL_ORIGINS = False  # Still use explicit list

    # Security warnings for development
    import warnings

    warnings.warn(
        "Running in DEBUG mode. Security features reduced. DO NOT use in production!",
        RuntimeWarning,
        stacklevel=2,
    )

    # Create logs directory if it doesn't exist
    import os

    os.makedirs(BASE_DIR / "logs", exist_ok=True)

